CREATE DATABASE inLockGames;
GO

USE inLockGames;
GO

CREATE TABLE tipoUsuario(
	idTipoUsuario		INT PRIMARY KEY IDENTITY
	,titulo				VARCHAR (255) UNIQUE NOT NULL
);
GO

CREATE TABLE usuario(
	idUsuario		INT PRIMARY KEY IDENTITY
	,email			VARCHAR (255) UNIQUE NOT NULL
	,senha			VARCHAR (255) NOT NULL
	,idTipoUsuario	INT FOREIGN KEY REFERENCES tipoUsuario(idTipoUsuario)
);
GO

CREATE TABLE estudio(
	idEstudio		INT PRIMARY KEY IDENTITY
	,nomeEstudio	VARCHAR (255) UNIQUE NOT NULL
);
GO

CREATE TABLE jogo(
	idJogo			INT PRIMARY KEY IDENTITY
	,nomeJogo		VARCHAR (255) UNIQUE NOT NULL
	,descricao		TEXT NOT NULL
	,dataLancamento	DATE NOT NULL
	,valor			DECIMAL (18,2) NOT NULL
	,idEstudio		INT FOREIGN KEY REFERENCES estudio(idEstudio)
);
GO